version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: stockdb
    restart: always
    environment:
      POSTGRES_PASSWORD: stock123
      POSTGRES_USER: stockuser
      POSTGRES_DB: stockdb
    ports:
      - "5432:5432"
